# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created: Wed Sep  9 11:49:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1106, 534)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.zmin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.zmin.setMinimum(-100000.0)
        self.zmin.setMaximum(1000000.0)
        self.zmin.setProperty("value", -10.0)
        self.zmin.setObjectName(_fromUtf8("zmin"))
        self.gridLayout.addWidget(self.zmin, 3, 1, 1, 1)
        self.xmax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.xmax.setMinimum(-100000.0)
        self.xmax.setMaximum(1000000.0)
        self.xmax.setProperty("value", 10.0)
        self.xmax.setObjectName(_fromUtf8("xmax"))
        self.gridLayout.addWidget(self.xmax, 1, 2, 1, 1)
        self.zmax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.zmax.setMinimum(-100000.0)
        self.zmax.setMaximum(1000000.0)
        self.zmax.setProperty("value", 10.0)
        self.zmax.setObjectName(_fromUtf8("zmax"))
        self.gridLayout.addWidget(self.zmax, 3, 2, 1, 1)
        self.ymax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.ymax.setMinimum(-100000.0)
        self.ymax.setMaximum(1000000.0)
        self.ymax.setProperty("value", 10.0)
        self.ymax.setObjectName(_fromUtf8("ymax"))
        self.gridLayout.addWidget(self.ymax, 2, 2, 1, 1)
        self.xmin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.xmin.setMinimum(-100000.0)
        self.xmin.setMaximum(1000000.0)
        self.xmin.setProperty("value", -10.0)
        self.xmin.setObjectName(_fromUtf8("xmin"))
        self.gridLayout.addWidget(self.xmin, 1, 1, 1, 1)
        self.ymin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.ymin.setMinimum(-100000.0)
        self.ymin.setMaximum(1000000.0)
        self.ymin.setProperty("value", -10.0)
        self.ymin.setObjectName(_fromUtf8("ymin"))
        self.gridLayout.addWidget(self.ymin, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.xdial = QtGui.QDial(self.centralwidget)
        self.xdial.setEnabled(False)
        self.xdial.setMinimum(0)
        self.xdial.setMaximum(10000)
        self.xdial.setProperty("value", 5000)
        self.xdial.setInvertedAppearance(False)
        self.xdial.setInvertedControls(False)
        self.xdial.setWrapping(False)
        self.xdial.setNotchTarget(25.0)
        self.xdial.setNotchesVisible(True)
        self.xdial.setObjectName(_fromUtf8("xdial"))
        self.horizontalLayout_3.addWidget(self.xdial)
        self.ydial = QtGui.QDial(self.centralwidget)
        self.ydial.setEnabled(False)
        self.ydial.setMinimum(0)
        self.ydial.setMaximum(10000)
        self.ydial.setProperty("value", 5000)
        self.ydial.setWrapping(False)
        self.ydial.setNotchTarget(25.0)
        self.ydial.setNotchesVisible(True)
        self.ydial.setObjectName(_fromUtf8("ydial"))
        self.horizontalLayout_3.addWidget(self.ydial)
        self.zdial = QtGui.QDial(self.centralwidget)
        self.zdial.setEnabled(False)
        self.zdial.setMinimum(0)
        self.zdial.setMaximum(10000)
        self.zdial.setProperty("value", 5000)
        self.zdial.setWrapping(False)
        self.zdial.setNotchTarget(25.0)
        self.zdial.setNotchesVisible(True)
        self.zdial.setObjectName(_fromUtf8("zdial"))
        self.horizontalLayout_3.addWidget(self.zdial)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.xled = QtGui.QLCDNumber(self.centralwidget)
        self.xled.setSmallDecimalPoint(False)
        self.xled.setNumDigits(6)
        self.xled.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.xled.setObjectName(_fromUtf8("xled"))
        self.verticalLayout_2.addWidget(self.xled)
        self.yled = QtGui.QLCDNumber(self.centralwidget)
        self.yled.setSmallDecimalPoint(False)
        self.yled.setNumDigits(6)
        self.yled.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.yled.setObjectName(_fromUtf8("yled"))
        self.verticalLayout_2.addWidget(self.yled)
        self.zled = QtGui.QLCDNumber(self.centralwidget)
        self.zled.setSmallDecimalPoint(False)
        self.zled.setNumDigits(6)
        self.zled.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.zled.setObjectName(_fromUtf8("zled"))
        self.verticalLayout_2.addWidget(self.zled)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.xmon = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmon.sizePolicy().hasHeightForWidth())
        self.xmon.setSizePolicy(sizePolicy)
        self.xmon.setMinimum(0)
        self.xmon.setMaximum(10000)
        self.xmon.setProperty("value", 5000)
        self.xmon.setTextVisible(False)
        self.xmon.setInvertedAppearance(False)
        self.xmon.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.xmon.setObjectName(_fromUtf8("xmon"))
        self.verticalLayout.addWidget(self.xmon)
        self.ymon = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymon.sizePolicy().hasHeightForWidth())
        self.ymon.setSizePolicy(sizePolicy)
        self.ymon.setMinimum(0)
        self.ymon.setMaximum(10000)
        self.ymon.setProperty("value", 5000)
        self.ymon.setTextVisible(False)
        self.ymon.setObjectName(_fromUtf8("ymon"))
        self.verticalLayout.addWidget(self.ymon)
        self.zmon = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zmon.sizePolicy().hasHeightForWidth())
        self.zmon.setSizePolicy(sizePolicy)
        self.zmon.setMinimum(0)
        self.zmon.setMaximum(10000)
        self.zmon.setProperty("value", 5000)
        self.zmon.setTextVisible(False)
        self.zmon.setObjectName(_fromUtf8("zmon"))
        self.verticalLayout.addWidget(self.zmon)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.xgrafo = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xgrafo.sizePolicy().hasHeightForWidth())
        self.xgrafo.setSizePolicy(sizePolicy)
        self.xgrafo.setObjectName(_fromUtf8("xgrafo"))
        self.horizontalLayout_4.addWidget(self.xgrafo)
        self.ygrafo = PlotWidget(self.centralwidget)
        self.ygrafo.setObjectName(_fromUtf8("ygrafo"))
        self.horizontalLayout_4.addWidget(self.ygrafo)
        self.zgrafo = PlotWidget(self.centralwidget)
        self.zgrafo.setObjectName(_fromUtf8("zgrafo"))
        self.horizontalLayout_4.addWidget(self.zgrafo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmd = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd.sizePolicy().hasHeightForWidth())
        self.cmd.setSizePolicy(sizePolicy)
        self.cmd.setObjectName(_fromUtf8("cmd"))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.cmd.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmd)
        self.cpar = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpar.sizePolicy().hasHeightForWidth())
        self.cpar.setSizePolicy(sizePolicy)
        self.cpar.setMinimumSize(QtCore.QSize(0, 20))
        self.cpar.setObjectName(_fromUtf8("cpar"))
        self.horizontalLayout.addWidget(self.cpar)
        self.butDo = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butDo.sizePolicy().hasHeightForWidth())
        self.butDo.setSizePolicy(sizePolicy)
        self.butDo.setObjectName(_fromUtf8("butDo"))
        self.horizontalLayout.addWidget(self.butDo)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Min", None))
        self.label_5.setText(_translate("MainWindow", "Max", None))
        self.label_3.setText(_translate("MainWindow", "Z", None))
        self.label_2.setText(_translate("MainWindow", "Y", None))
        self.label.setText(_translate("MainWindow", "X", None))
        self.xmon.setFormat(_translate("MainWindow", "%v", None))
        self.ymon.setFormat(_translate("MainWindow", "%v", None))
        self.zmon.setFormat(_translate("MainWindow", "%v", None))
        self.cmd.setItemText(0, _translate("MainWindow", "Z", None))
        self.cmd.setItemText(1, _translate("MainWindow", "Y", None))
        self.cmd.setItemText(2, _translate("MainWindow", "D", None))
        self.cmd.setItemText(3, _translate("MainWindow", "P", None))
        self.cmd.setItemText(4, _translate("MainWindow", "K", None))
        self.cmd.setItemText(5, _translate("MainWindow", "s", None))
        self.cmd.setItemText(6, _translate("MainWindow", "g", None))
        self.cmd.setItemText(7, _translate("MainWindow", "8", None))
        self.cmd.setItemText(8, _translate("MainWindow", "R", None))
        self.butDo.setText(_translate("MainWindow", "GO", None))

from pyqtgraph import PlotWidget
